// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WebTerrae.Data.Data
{
    public partial class Empleados
    {
        public Empleados()
        {
            Carnets = new HashSet<Carnets>();
            SubscripcionEmpleadoOferta = new HashSet<SubscripcionEmpleadoOferta>();
        }

        public int EmpleadoId { get; set; }
        public string Nombre { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public DateTime? FechaNacimiento { get; set; }
        public string Identidad { get; set; }
        public string NumeroTelefono { get; set; }
        public string Direccion { get; set; }
        public string Provincia { get; set; }

        public virtual ExperienciaLaboral ExperienciaLaboral { get; set; }
        public virtual ICollection<Carnets> Carnets { get; set; }
        public virtual ICollection<SubscripcionEmpleadoOferta> SubscripcionEmpleadoOferta { get; set; }
    }
}