// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WebTerrae.Data.Data
{
    public partial class ExperienciaLaboral
    {
        public int ExperienciaLaboralId { get; set; }
        public string Descripcion { get; set; }
        public DateTime? FechaFinal { get; set; }
        public DateTime? FechaInicio { get; set; }
        public int EmpleadoId { get; set; }

        public virtual Empleados Empleado { get; set; }
    }
}