// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WebTerrae.Data.Data
{
    public partial class Ofertas
    {
        public Ofertas()
        {
            SubscripcionEmpleadoOferta = new HashSet<SubscripcionEmpleadoOferta>();
        }

        public int OfertaId { get; set; }
        public string Descripcion { get; set; }
        public DateTime? FechaInicio { get; set; }
        public int? NumeroCandidatos { get; set; }
        public string Provincia { get; set; }
        public string Titulo { get; set; }

        public virtual ICollection<SubscripcionEmpleadoOferta> SubscripcionEmpleadoOferta { get; set; }
    }
}